name: Demo workflow
on: workflow_dispatch     
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
    - name: print to console 
      run: echo Hello GH Actions
  bud:
    runs-on: ubuntu-latest
    steps:
      - name: print adlan
        run: echo adlan hello world
      
